from pydantic import BaseModel
from typing import Optional

from .schemas import (
    DoctorBase,
    DoctorCreate,
    DoctorResponse,
    DoctorLogin,
    Token,
    TokenPayload,
    WeeklyScheduleBase,
    WeeklyScheduleCreate,
    WeeklyScheduleResponse,
    SlotBase,
    SlotResponse,
    SlotWithDoctor,
    BookingBase,
    BookingCreate,
    BookingResponse,
    ChatMessage,
    ChatResponse,
    PaymentIntentResponse,
    CancellationConfirm,
    UpgradationResponse,
    AvailableSlotSearch,
    BlockSlotRequest,
)

__all__ = [
    "DoctorBase",
    "DoctorCreate",
    "DoctorResponse",
    "DoctorLogin",
    "Token",
    "TokenPayload",
    "WeeklyScheduleBase",
    "WeeklyScheduleCreate",
    "WeeklyScheduleResponse",
    "SlotBase",
    "SlotResponse",
    "SlotWithDoctor",
    "BookingBase",
    "BookingCreate",
    "BookingResponse",
    "ChatMessage",
    "ChatResponse",
    "PaymentIntentResponse",
    "CancellationConfirm",
    "UpgradationResponse",
    "AvailableSlotSearch",
    "BlockSlotRequest",
]